variables = [
    "APPROVALS_TEAM",
    "AWS_ACCOUNT_ID",
    "AWS_PLANNED_EXPENSE",
    "AWS_REGION",
    "CLIENT",
    "CLOUDFLARE_API_TOKEN",
    "COMPONENTS",
    "CREATED_BY",
    "CREATED_DATE",
    "DATABASE_ENGINE",
    "DATABASE_VERSION",
    "DATE",
    "DEFAULT_SSL_SECRET",
    "DNS_MANAGEMENT",
    "DNS_PROVIDER",
    "DOMAIN",
    "EFSID",
    "ENVIRONMENT",
    "FULL_PROJECT_NAME",
    "GITHUB_TEAM",
    "GITHUB_TEAM_EXPLANATIONS",
    "GITHUB_TEAM_IDS",
    "HAVESLA",
    "HELM_APP_ALERTMANAGER",
    "HELM_APP_ARGO-CD",
    "HELM_APP_TELEPORT",
    "HELM_APP_VELERO",
    "HELM_ARGO-CD",
    "HELM_AWS-EBS-CSI-DRIVER",
    "HELM_AWS-EFS-CSI-DRIVER",
    "HELM_CERT-MANAGER",
    "HELM_DESCHEDULER",
    "HELM_EXTERNAL-DNS",
    "HELM_GRAFANA",
    "HELM_INGRESS-NGINX",
    "HELM_KUBERNETES-EVENT-EXPORTER",
    "HELM_KUBEWATCH",
    "HELM_KUBE_DOWNSCALER",
    "HELM_LOKI",
    "HELM_MAILHOG",
    "HELM_METRICS_SERVER",
    "HELM_MYSQL-EXPORTER",
    "HELM_OPENTELEMETRY-COLLECTOR",
    "HELM_POSTGRES-EXPORTER",
    "HELM_PROMETHEUS",
    "HELM_PROMTAIL",
    "HELM_RELOADER",
    "HELM_SARITASA-MAINTENANCE",
    "HELM_SARITASA-OPSGENIE",
    "HELM_SARITASA-RBAC",
    "HELM_TEKTON-APPS",
    "HELM_TEKTON-ENGINE",
    "HELM_TEKTON-PIPELINES",
    "HELM_TELEPORT",
    "HELM_TEMPO",
    "HELM_TWINGATE",
    "HELM_VELERO",
    "JIRA_PROJECT",
    "LATEST_SARITASA_TERRAFORM_RELEASE",
    "LATEST_TERRAFORM_RELEASE",
    "NAT_GW_1",
    "NAT_GW_2",
    "NAT_GW_3",
    "OAUTH_GRAFANA_CLIENT_ID",
    "OAUTH_GRAFANA_SECRET_ID",
    "OAUTH_TELEPORT_CLIENT_ID",
    "OAUTH_TELEPORT_SECRET_ID",
    "OPSGENIE_APIKEY",
    "OPSGENIE_PROMETHEUS_APIKEY",
    "OPS_HUMAN",
    "OPS_MAIN",
    "OPS_SECONDARY",
    "OPS_TEAM",
    "PIPELINES_ENABLED",
    "PIPELINE_DJANGO",
    "PIPELINE_DOTNET",
    "PIPELINE_FRONTEND",
    "PIPELINE_GO",
    "PIPELINE_JAVA",
    "PIPELINE_KANIKO",
    "PIPELINE_NODEJS",
    "PIPELINE_PHP",
    "PIPELINE_RUBY",
    "PM_EMAIL",
    "PM_NAME",
    "PROJECT",
    "PROJECT_COMPONENTS",
    "PROJECT_MANAGER",
    "PROJECT_NAME",
    "PROVISIONS",
    "RDS_DB_HOST",
    "RDS_DB_PASS",
    "RDS_DB_USER",
    "REDIS_HOST",
    "REDIS_PORT",
    "REPOSITORY",
    "SARITASA_AWS_ACCOUNT_ID",
    "SARITASA_AWS_REGION",
    "SLACK_CLIENT_ALARMS_WEBHOOK_URL",
    "SLACK_CLIENT_DEPLOYMENTS_WEBHOOK_URL",
    "SLACK_CLIENT_PROJECT_WEBHOOK_URL",
    "SLACK_TEAM_DEVOPS_EOL_WEBHOOK_URL",
    "SMTP_GRAFANA_EMAIL_FROM",
    "SMTP_GRAFANA_EMAIL_HOST",
    "SMTP_GRAFANA_ENABLED",
    "SMTP_GRAFANA_PASSWORD",
    "SMTP_GRAFANA_USER",
    "TECHNICAL_MANAGER",
    "TELEPORT_AGENT_ENABLED",
    "TELEPORT_AGENT_JOIN_TOKEN",
    "TELEPORT_CLUSTER_ENABLED",
    "TERRAFORM_AWS_PROVIDER_VERSION",
    "TERRAFORM_CREATE_DOCKER_IMAGES_REPO",
    "TERRAFORM_CREATE_DOCS_REPO",
    "TERRAFORM_CREATE_KUBERNETES_REPO",
    "TERRAFORM_CREATE_TERRAFORM_REPO",
    "TERRAFORM_GITHUB_PROVIDER_VERSION",
    "TERRAFORM_KUBECTL_PROVIDER_VERSION",
    "TERRAFORM_KUBERNETES_PROVIDER_VERSION",
    "TERRAFORM_MSSQL_PROVIDER_VERSION",
    "TERRAFORM_MYSQL_PROVIDER_VERSION",
    "TERRAFORM_NULL_LABEL_VERSION",
    "TERRAFORM_NULL_PROVIDER_VERSION",
    "TERRAFORM_POSTGRESQL_PROVIDER_VERSION",
    "TERRAFORM_RANDOM_PROVIDER_VERSION",
    "TERRAFORM_SARITASA_ARGOCD_WORDPRESS_SECRETS_VERSION",
    "TERRAFORM_SARITASA_CLIENT_VERSION",
    "TERRAFORM_SARITASA_CONFIG_VERSION",
    "TERRAFORM_SARITASA_GITHUB_VERSION",
    "TERRAFORM_SARITASA_GITHUB_WEBHOOK_VERSION",
    "TERRAFORM_SARITASA_PROJECT_ENVIRONMENT_RESOURCES_VERSION",
    "TERRAFORM_SARITASA_PROJECT_INFRA_VERSION",
    "TERRAFORM_SARITASA_PROJECT_VERSION",
    "TERRAFORM_SENTRY_PROVIDER_VERSION",
    "TERRAFORM_USE_DEV_REPO",
    "TM_NAME",
    "TWINGATE_ACCESS_TOKEN",
    "TWINGATE_REFRESH_TOKEN",
    "UPPER_FULL_PROJECT_NAME",
    "WHO_IS_LEAD_DEVS"
]
