-   id: check-nginx-wide-range
    name: check wide `try_files` directive
    description: prevents from committing nginx configs with wide `try_files` directives without disabled locations
    entry: check-nginx-wide-range
    language: python
    stages: [commit, push, manual]
